FROM nginx:latest

COPY /root/kubernetes-ci-cd/applications/hello-kenzan/index.html /usr/share/nginx/html/index.html
COPY /root/kubernetes-ci-cd/applications/hello-kenzan/DockerFileEx.jpg /usr/share/nginx/html/DockerFileEx.jpg

EXPOSE 80
