FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY DockerFileEx.jpg /usr/share/nginx/html/DockerFileEx.jpg
COPY BengalCat.jpg /usr/share/nginx/html/BengalCat.jpg
COPY Forge.jpg /usr/share/nginx/html/Forge.jpg

EXPOSE 80
