node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-kenzan"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    env.BUILD_TAG=tag

    stage "Build"
    
        sh "docker build -t 127.0.0.1:30400/hello-kenzan:latest part1/hello-kenzan"
    
    stage "Push"

        sh "docker push 127.0.0.1:30400/hello-kenzan:latest"

    stage "Deploy"

        sh "sed 's#__IMAGE__#'$BUILDIMG'#' part1/hello-kenzan/k8s/deployment.yaml | kubectl apply -f -"

    stage "Test"

        sh "curl -sL -w "%{http_code}\\n" "http://204.212.162.26:31683/" -o /dev/null --connect-timeout 3 --max-time 5 | grep 200"

}
